MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  NAME: "Mapillary"
  TRAIN: ("mapillary_vistas_panoptic_train_cropsampling",)
  TEST: ("mapillary_vistas_panoptic_val_cropsampling",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MAX_ITER: 300000
  CHECKPOINT_PERIOD: 30000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 2048) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TRAIN: 8192
  MAX_SIZE_TEST: 2048
  NEW_SAMPLING: True
  NEW_SAMPLING_SHORTEST_SIDE_MIN: 1024
  NEW_SAMPLING_SHORTEST_SIDE_MAX: 6192
  NEW_SAMPLING_OVERALL_MAX_SIZE : 9288
  SCALE_OPTIONS: [32, 64, 128, 256, 512]
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (1024, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
    WITH_INSTANCE: True
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 1024  # used in dataset mapper
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_panoptic_cropsampling"
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 10
VERSION: 2
